
export type Therapy = {
  id: string;
  slug: string;
  name: string;
  imageUrl: string;
  what: string;
  why: string;
  who: string;
  benefits: string[];
  bodyParts: string;
  duration: string;
};

export const therapiesData: Therapy[] = [
  {
    id: 't2',
    name: 'Abhyangam',
    slug: 'abhyangam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fabhyangam.webp?alt=media&token=e64e1510-c56b-4088-9b17-9c36603d59ac',
    what: 'Abhyangam is a traditional Ayurvedic full-body oil massage performed using warm medicated herbal oils. It involves rhythmic, synchronized strokes that balance the doshas, nourish the tissues (dhatus), and promote overall wellness. It is one of the most commonly practiced Purvakarma (pre-operative procedures) in Panchakarma.',
    why: 'Abhyangam is done to:\nImprove circulation and lymphatic flow,\nLubricate joints and tissues,\nReduce stress and calm the nervous system,\nPrepare the body for detox therapies like Svedana and Panchakarma,',
    who: 'Individuals with stress, anxiety, or sleep disturbances\n\nPeople with body pain, muscle stiffness, or joint issues\n\nThose with dry skin or Vata aggravation\n\nPeople with sedentary lifestyles or long working hours\n\nElderly individuals needing nourishment and mobility support\n\nAnyone seeking general wellness, relaxation, or preventive care',
    benefits: [
      'Relieves muscle pain, fatigue, and stiffness',
      'Enhances blood circulation and lymphatic drainage',
      'Improves digestion and metabolism',
      'Promotes better sleep and mental relaxation',
      'Nourishes skin and delays ageing',
      'Strengthens muscles, ligaments, and joints',
      'Boosts immunity and improves overall vitality',
      'Helps in balancing Vata dosha.',
    ],
    bodyParts: 'Full body: Head to toe \nSpecific regions:Shiro Abhyanga (head),Mukha Abhyanga (face),Greeva Abhyanga (neck),Prishta Abhyanga (back),Pada Abhyanga (feet),Hasta Abhyanga (hands),Joint-focused areas (knee, shoulder, etc.)',
    duration: 'Typical session: 45–60 minutes\nFor therapeutic cases: 60–90 minutes\nUsually advised as a 7, 14, or 21-day course depending on the condition and goal',
  },
  {
    id: 't10',
    name: 'Swedana',
    slug: 'swedana',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fswedana.webp?alt=media&token=d0ec91b3-263d-4b67-8c47-2af24aa1ffeb',
    what: 'Swedanam is an Ayurvedic therapy that induces sweating using steam, warm herbal decoctions, or heat packs. It is done after oil application to open the channels (srotas), loosen toxins, and prepare the body for detoxification. It is considered a key Purvakarma procedure before Panchakarma.',
    why: 'Swedanam is performed to:Dilate the channels and remove stiffness;Mobilize and expel toxins (ama);Prepare the body for Vamana, Virechana, and other Panchakarma therapies;Relieve pain, heaviness, and coldness caused by Vata–Kapha imbalance;Promote better absorption of medicated oils applied in prior treatments.',
    who: 'It is beneficial for people with:Body stiffness, muscle tightness, or joint pain;Respiratory congestion (Kapha disorders);Heaviness or swelling in the body.',
    benefits: [
      'Relieves pain, stiffness, and muscle tension',
      'Improves circulation',
      'Promotes detoxification by mobilizing ama',
      'Reduces swelling',
      'Helps in Kapha reduction (decreases heaviness, congestion)',
      'Enhances penetration of medicated oils.',
    ],
    bodyParts: 'It can be done on Full body or locally also depending on the condition of the patient',
    duration: 'Typical session: 20–30 minutes (depending on body type and heat tolerance)\nOften done as a 3, 5, 7, 14, or 21-day course as part of a Panchakarma plan.',
  },
  {
    id: 't5',
    name: 'Shirodhara',
    slug: 'shirodhara',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fshirodhara.webp?alt=media&token=3eae7a87-b9aa-4c45-ae33-14be8931d376',
    what: 'Shirodhara is a classical Ayurvedic therapy in which a continuous, gentle stream of warm medicated liquid (oil, buttermilk, milk, or decoctions) is poured over the forehead. It is considered a prime therapy for Manasika (mind-related) and neurological disorders.',
    why: 'Shirodhara is performed to calm the mind, reduce stress, and relax the nervous system.\nIt helps balance Vata and Pitta, improves sleep, eases headaches, and brings mental clarity.\nIn simple words — it gives deep relaxation, reduces overthinking, and supports emotional balance.',
    who: 'It is beneficial for individuals with:\nStress, anxiety, or overthinking;Insomnia or disturbed sleep;Chronic headaches or migraines;Hypertension due to stress;Hormonal fluctuations influenced by stress.',
    benefits: [
      'calming the mind and reducing mental stress',
      'inducing natural, sound sleep',
      'balancing aggravated doshas',
      'relieving headaches and migraine-like pain',
      'nourishing scalp and improving hair health',
      'enhancing memory, concentration, and mental clarity',
      'soothing sense organs',
      'restoring body–mind balance.',
    ],
    bodyParts: 'The therapy focuses on the forehead and scalp.',
    duration: 'A session lasts 30–45 minutes.\nA course may be advised for 7–14 days depending on the condition.',
  },
  {
    id: 't8',
    name: 'Pizhichil',
    slug: 'pizhichil',
    imageUrl: 'http://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fpizhichil.webp?alt=media&token=89bc2874-5427-4bff-a78d-a647d176f14a',
    what: 'Pizhichil is a traditional Ayurvedic rejuvenation therapy where warm medicated herbal oils are poured continuously over the body while performing a gentle massage. This combination of oil pouring and massage deeply nourishes the tissues, relaxes muscles, and revitalizes both the body and mind. It is renowned for its calming and restorative effects.',
    why: 'Pizhichil is performed to relax the muscles, calm the nervous system, and promote overall rejuvenation. The warm herbal oils penetrate deep into the tissues, enhancing circulation, reducing stiffness, and alleviating stress. It also helps in detoxifying the body and improving flexibility.',
    who: 'This therapy is recommended for individuals suffering from chronic joint pain, muscular stiffness, neurological disorders, stress, fatigue, or those seeking complete relaxation and rejuvenation. It is especially beneficial for people with arthritis, sciatica, or those recovering from injuries.',
    benefits: [
      'relief from joint and muscle pain',
      'improved flexibility',
      'enhanced blood circulation',
      'stress reduction',
      'detoxification',
      'overall rejuvenation. It also nourishes the skin',
      'promotes mental relaxation',
      'strengthens the nervous system.',
    ],
    bodyParts: 'Pizhichil is a full-body therapy, with special attention given to the back, shoulders, joints, and limbs. The warm oil is poured continuously over the entire body while performing rhythmic massage movements to ensure maximum therapeutic effect.',
    duration: 'A typical Pizhichil session lasts between 45 to 60 minutes, depending on the individual’s needs and health condition. Multiple sessions are recommended for chronic conditions or deep rejuvenation.',
  },
  {
    id: 't9',
    name: 'Navarakizhi',
    slug: 'navarakizhi',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fnavarakizhi.webp?alt=media&token=a37586c5-0ff6-44d1-a685-a752fdd47b13',
    what: 'Navarakizhi is a rejuvenating Ayurvedic therapy that involves massaging the body with warm herbal pouches (Kizhi) filled with cooked medicinal rice (Navara) and herbal decoctions. The therapy combines heat, herbal nutrients, and massage to nourish the body, relax muscles, and promote overall wellness.',
    why: 'Navarakizhi is performed to improve strength, stamina, and vitality while alleviating muscle stiffness and joint discomfort. The warm herbal pouches enhance circulation, detoxify the tissues, and provide deep nourishment to the skin, muscles, and joints.',
    who: 'This therapy is recommended for individuals experiencing muscular weakness, joint pain, degenerative conditions, fatigue, or general body stiffness. It is also beneficial for those seeking rejuvenation, improved vitality, and relief from chronic aches or post-injury recovery.',
    benefits: [
      'relief from muscular pain and stiffness',
      'improved joint flexibility',
      'enhanced blood circulation',
      'strengthened muscles',
      'deep tissue nourishment',
      'overall rejuvenation. It also promotes better skin texture and supports vitality and energy levels.',
    ],
    bodyParts: 'Navarakizhi is a full-body therapy, focusing on major muscle groups, joints, and areas of stiffness. The warm herbal pouches are applied over the entire body to provide therapeutic and nourishing effects.',
    duration: 'A typical Navarakizhi session is usually performed daily for 7 to 14 days, with each session lasting about 45 to 60 minutes, depending on the individual’s health condition and therapeutic needs.',
  },
  {
    id: 't1',
    name: 'Podikizhi',
    slug: 'podikizhi',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fpodikizhi.webp?alt=media&token=01b91345-f424-4d54-bdea-22b24ddca91f',
    what: 'Podikizhi is an Ayurvedic therapy that involves massaging the body with warm herbal Kizhi (pouches) filled with medicinal powders. These herbal pouches are applied in rhythmic strokes over the body to stimulate circulation, detoxify tissues, relieve stiffness, and revitalize muscles and joints.',
    why: 'Podikizhi is performed to relieve muscular stiffness, reduce fatigue, and improve blood circulation. The herbal powders penetrate the skin, remove toxins, and rejuvenate the body while promoting relaxation and overall wellness.',
    who: 'This therapy is recommended for individuals experiencing muscular pain, stiffness, arthritis, fatigue, or general body weakness. It is also beneficial for those seeking improved mobility, enhanced muscle strength, and relaxation.',
    benefits: [
      'relief from muscle pain and stiffness',
      'improved circulation',
      'enhanced joint flexibility',
      'detoxification of tissues',
      'overall rejuvenation. It also helps in strengthening muscles and improving body tone.',
    ],
    bodyParts: 'Podikizhi is a full-body therapy that primarily targets major muscle groups, joints, and areas with stiffness or fatigue. The warm herbal Kizhi are applied throughout the body to provide therapeutic and revitalizing effects.',
    duration: 'A typical Podikizhi session lasts for 30 to 45 minutes, depending on the individual’s condition and therapeutic needs.',
  },
  {
    id: 't17',
    name: 'Elakizhi',
    slug: 'elakizhi',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Felakizhi.webp?alt=media&token=8724c1cf-65b6-4ee0-ac25-83a01b1bfc78',
    what: 'Elakizhi is a traditional Ayurvedic therapy where warm herbal leaves are processed with medicinal oils and bundled into therapeutic pouches (kizhi). These heated pouches are gently massaged over the body, delivering deep nourishment, improved mobility, and relief from chronic pain. Elakizhi works by opening the pores, enhancing circulation, and easing stiffness, making it one of the most rejuvenating and revitalizing therapies in Ayurveda.',
    why: 'Elakizhi is done to ease chronic pain, reduce inflammation, and rejuvenate stiff or fatigued muscles. The warmth of the kizhi helps open the channels, allowing herbal extracts to penetrate deeper and promote healing. It is also used to stimulate blood flow, detoxify tissues, and restore physical strength in people with long-standing musculoskeletal discomfort.',
    who: 'This therapy is ideal for individuals experiencing joint pain, muscle stiffness, arthritis-related discomfort, back pain, or post-injury soreness. It is also recommended for people with reduced flexibility, sports-related strain, or those who feel tired, heavy, and weak in the body.',
    benefits: [
      'relieve pain',
      'reduce swelling',
      'relax tight muscles. It improves flexibility',
      'enhances blood circulation',
      'supports faster recovery from injuries. The therapy also detoxifies tissues',
      'strengthens joints',
      'provides a deep sense of relaxation',
      'making the body feel lighter',
      'warmer',
      'and more energetic after the session.',
    ],
    bodyParts: 'Elakizhi can be performed on the whole body or on specific areas depending on the condition. Common regions include the back, neck, shoulders, knees, hips, arms, and feet. Targeted therapy is done when pain or stiffness is localized, while full-body therapy is recommended for widespread discomfort or general rejuvenation.',
    duration: 'A typical Elakizhi session lasts 30–45 minutes, with the kizhi kept consistently warm throughout the treatment. For therapeutic results, it is usually advised as a course of 7–14 days, depending on the severity of symptoms and the individual’s healing response.',
  },
  {
    id: 't6',
    name: 'Udvarthanam',
    slug: 'udvarthanam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fudvarthanam.webp?alt=media&token=db1f0dc0-152b-4518-99a5-2593e55ab430',
    what: 'Udwartanam is an Ayurvedic therapy that involves a vigorous massage of the body using herbal powders. The treatment is performed with specially prepared powders made from herbs that are known for their stimulating and detoxifying properties. It is usually done in a dry form without oils, focusing on rubbing and massaging the powder onto the skin in upward, circular, and linear motions to activate circulation and metabolism.',
    why: 'Udwartanam is performed to reduce excess fat, improve blood and lymph circulation, and remove toxins from the body. The massage stimulates the skin and underlying tissues, enhancing metabolic activity and promoting overall wellness. It is considered effective for detoxification and improving skin texture while also energizing the body.',
    who: 'This therapy is recommended for individuals who are overweight, have localized fat deposits, experience lethargy, or suffer from sluggish metabolism. It is also beneficial for people dealing with cellulite, obesity, or mild muscular stiffness. Those looking to improve skin tone and circulation can also benefit from Udwartanam.',
    benefits: [
      'weight management',
      'improved skin texture',
      'detoxification',
      'increased energy levels',
      'reduction of cellulite',
      'relief from muscular stiffness. Regular sessions can also boost circulation',
      'stimulate fat metabolism',
      'rejuvenate both body and mind.',
    ],
    bodyParts: 'Udwartanam primarily targets areas with excess fat deposits, including the abdomen, thighs, arms, and back. However, the therapy also improves circulation and stimulates the skin throughout the entire body, promoting overall rejuvenation.',
    duration: 'A typical Udwartanam session lasts between 30 to 60 minutes, depending on the individual’s body type, condition, and specific needs. Multiple sessions may be recommended for achieving optimal results.',
  },
  {
    id: 't4',
    name: 'Kati Vasti',
    slug: 'kati-vasti',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fkati-vasti.webp?alt=media&token=faa9c3e3-bf2f-4eb9-95a3-4ebe030f9808',
    what: 'Kati Vasti is an Ayurvedic therapy that involves pouring and retaining warm medicated oil over the lower back (lumbar region) in a specially made dough ring. The warm oil penetrates deep into the muscles, joints, and nerves of the lower back, providing targeted relief and nourishment to the affected area.',
    why: 'Kati Vasti is performed to relieve lower back pain, stiffness, and inflammation. The warm medicated oil helps relax tight muscles, improves blood circulation in the lumbar region, reduces inflammation, and supports spinal health. It is considered highly effective for chronic back issues.',
    who: 'This therapy is recommended for individuals suffering from chronic lower back pain, sciatica, slipped disc, lumbar spondylosis, or muscle stiffness. It is also beneficial for people experiencing nerve-related discomfort or spinal tension due to sedentary lifestyle or injury.',
    benefits: [
      'relief from chronic lower back pain',
      'reduced stiffness',
      'improved flexibility',
      'strengthened lumbar muscles',
      'enhanced circulation. It also promotes relaxation',
      'reduces nerve compression',
      'helps in overall spinal health.',
    ],
    bodyParts: 'Kati Vasti specifically targets the lower back (lumbar region), including muscles, vertebrae, and nerves in that area.',
    duration: 'A typical Kati Vasti session lasts between 30 to 45 minutes, depending on the severity of the condition. Multiple sessions may be recommended for chronic issues to achieve lasting relief.',
  },
  {
    id: 't3',
    name: 'Greeva Vasti',
    slug: 'greeva-vasti',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fgreeva-basti.webp?alt=media&token=7aa1ffa6-6210-44a9-8735-5a477b72e999',
    what: 'Greeva Vasti is an Ayurvedic therapy that involves retaining warm medicated oil on the neck area using a specially prepared dough ring. The oil is gently poured and allowed to stay over the cervical region to penetrate the muscles, joints, and nerves of the neck. This therapy is highly effective in relieving stiffness and promoting flexibility in the neck and shoulder region.',
    why: 'Greeva Vasti is performed to alleviate neck pain, stiffness, and tension. The warm herbal oils soothe muscles, reduce inflammation, improve blood circulation, and help relax the nervous system. It also supports spinal health and enhances mobility in the cervical region.',
    who: 'This therapy is recommended for individuals suffering from chronic neck pain, cervical spondylosis, stiffness, nerve compression, tension headaches, or muscular tightness in the neck and shoulders. It is also suitable for those with a sedentary lifestyle or prolonged desk work.',
    benefits: [
      'relief from neck pain and stiffness',
      'improved flexibility and range of motion',
      'reduced inflammation',
      'enhanced circulation',
      'relaxation of the nervous system. It also promotes overall spinal health and helps prevent further degenerative changes.',
    ],
    bodyParts: 'Greeva Vasti specifically targets the neck (cervical region) and upper shoulders, nourishing the muscles, joints, and nerves in this area.',
    duration: 'A typical Greeva Vasti session lasts between 30 to 45 minutes, depending on the severity of the condition. Multiple sessions may be recommended for chronic issues to achieve long-lasting relief.',
  },
  {
    id: 't7',
    name: 'Janu Vasti',
    slug: 'janu-vasti',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fjanu-basti.webp?alt=media&token=6adc1450-86c0-4e1b-80df-e08fbb10bc92',
    what: 'Janu Vasti is an Ayurvedic therapy that involves retaining warm medicated oil over the knee joint using a specially prepared dough ring. The therapy focuses on allowing the herbal oils to penetrate deeply into the knee joint, muscles, and surrounding tissues, providing nourishment and relieving stiffness. It is considered highly effective for knee-related problems and joint rejuvenation.',
    why: 'Janu Vasti is performed to relieve knee pain, stiffness, and inflammation. The warm herbal oils improve circulation, relax the muscles, reduce swelling, and help in the lubrication of joints. It also supports cartilage health and enhances overall mobility of the knee.',
    who: 'This therapy is recommended for individuals suffering from knee pain, arthritis, ligament injuries, joint stiffness, swelling, or degenerative joint conditions. It is also beneficial for those experiencing discomfort due to aging or repetitive strain on the knees.',
    benefits: [
      'relief from knee pain and stiffness',
      'improved joint flexibility and mobility',
      'reduced inflammation',
      'strengthened muscles around the knee',
      'enhanced blood circulation. It also promotes nourishment of the joint tissues and overall knee health.',
    ],
    bodyParts: 'Janu Vasti specifically targets the knee joint and surrounding muscles and ligaments. The warm medicated oil penetrates deep into the tissues, providing therapeutic and rejuvenating effects.',
    duration: 'A typical Janu Vasti session lasts between 30 to 45 minutes, depending on the condition and individual needs. Multiple sessions may be recommended for chronic knee problems to achieve lasting relief.',
  },
  {
    id: 't13',
    name: 'Nasyam',
    slug: 'nasyam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fnasyam.webp?alt=media&token=2bdf5c29-cedb-4ff9-9705-e3626020c6cd',
    what: 'Nasyam is an Ayurvedic therapy that involves administering medicated herbal oils, powders, or juices through the nasal passages. This treatment helps cleanse, lubricate, and balance the head and neck region, including the sinuses, throat, and brain. It is considered one of the most effective therapies for maintaining respiratory and neurological health',
    why: 'Nasyam is performed to clear nasal passages, improve sinus health, and balance the doshas in the head region. The therapy helps in detoxifying the upper respiratory tract, reducing congestion, alleviating headaches, and enhancing mental clarity. It also supports overall wellness of the brain and senses.',
    who: 'This therapy is recommended for individuals suffering from sinusitis, chronic cold, headaches, migraine, nasal congestion, sleep disorders, or stress-related conditions. It is also beneficial for those seeking improved mental focus, clarity, and relief from neurological discomforts.',
    benefits: [
      'relief from nasal congestion',
      'improved sinus function',
      'reduction of headaches and migraines',
      'enhanced mental clarity and focus',
      'relaxation of the nervous system',
      'better overall respiratory health. It also nourishes the sensory organs and maintains balance in the head region.',
    ],
    bodyParts: 'Nasyam primarily targets the head, nasal passages, sinuses, throat, and brain. The medicated oils and herbal preparations penetrate these areas to provide therapeutic and rejuvenating effects.',
    duration: 'A typical Nasyam session lasts between 15 to 30 minutes, depending on the type of preparation and the individual’s condition. Multiple sessions may be recommended for chronic sinus or neurological issues.',
  },
  {
    id: 't19',
    name: 'Vamana',
    slug: 'vamana',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2FVamana.webp?alt=media&token=02731b7f-71b8-48e1-8d2b-a3668dafc7a6',
    what: 'Vamana Therapy is a classical Ayurvedic treatment for therapeutic vomiting that involves the controlled induction of vomiting using herbal decoctions. This therapy is primarily aimed at eliminating excess Kapha (phlegm) from the body, detoxifying the system, and restoring balance to the doshas.',
    why: 'Vamana is performed to cleanse the respiratory and digestive systems, remove toxins, and correct imbalances caused by excess Kapha. It helps in strengthening the digestive fire (Agni), improving metabolism, and preventing the onset of chronic disorders related to Kapha imbalance.',
    who: 'This therapy is recommended for individuals suffering from respiratory issues like chronic cold, sinusitis, asthma, obesity, indigestion, or Kapha-related disorders. It is also beneficial for those seeking detoxification, rejuvenation, and improved immunity.',
    benefits: [
      'elimination of toxins',
      'improved digestion and metabolism',
      'relief from respiratory congestion',
      'strengthened immunity',
      'overall rejuvenation. It also helps in maintaining a balanced mind-body system and preventing Kapha-related disorders.',
    ],
    bodyParts: 'Vamana primarily targets the respiratory tract, digestive system, and upper gastrointestinal tract. By expelling accumulated Kapha, it supports the health of the lungs, stomach, and overall metabolism.',
    duration: 'A typical Vamana Therapy course lasts for 3 to 7 days, depending on the individual’s condition, body type, and health requirements. Each session is closely supervised by an Ayurvedic practitioner to ensure safety and effectiveness.',
  },
  {
    id: 't29',
    name: 'Virechana',
    slug: 'virechana',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fvirechana.webp?alt=media&token=d9a78447-300f-4012-8315-b7c3c865dd83',
    what: 'Virechana Therapy is a classical Ayurvedic purgation treatment that involves the controlled use of herbal laxatives to cleanse the body of excess Pitta and toxins. The therapy helps detoxify the liver, intestines, and digestive system while restoring balance to the doshas.',
    why: 'Virechana is performed to remove accumulated Pitta toxins, improve digestive health, and support liver function. It helps in balancing metabolic processes, preventing skin and digestive disorders, and promoting overall wellness.',
    who: 'This therapy is recommended for individuals suffering from skin disorders, acidity, digestive issues, liver problems, hyperacidity, or Pitta-related imbalances. It is also beneficial for those seeking detoxification, rejuvenation, and improved digestion.',
    benefits: [
      'elimination of Pitta toxins',
      'improved digestion and metabolism',
      'relief from acidity and liver-related disorders',
      'better skin health',
      'overall rejuvenation. It also helps maintain balanced energy levels and prevents Pitta-related ailments.',
    ],
    bodyParts: 'Virechana primarily targets the liver, intestines, and digestive tract. By clearing accumulated Pitta and toxins, it supports healthy metabolism, digestion, and overall gastrointestinal function.',
    duration: 'A typical Virechana Therapy course lasts for 3 to 7 days, depending on the individual’s health condition and body constitution. Each session is conducted under careful supervision by an Ayurvedic practitioner to ensure safety and effectiveness.',
  },
  {
    id: 't21',
    name: 'Basti',
    slug: 'basti',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fbasti.webp?alt=media&token=a369202c-d9d3-41d0-ad41-7ef689a964d6',
    what: 'Vasti, also known as Basti, is an important Ayurvedic cleansing and rejuvenation therapy in which medicated oils, herbal decoctions, or herbal milk preparations are administered through the rectal route. It is considered one of the most effective therapies for balancing the body, especially disorders related to digestion, elimination, nerves, and joints. The formulation used is selected based on the individual’s health condition.',
    why: 'According to Ayurveda, many chronic health issues arise due to imbalance in the body’s movement and elimination processes. Vasti therapy helps cleanse the colon, support proper bowel function, and nourish tissues. It is widely used in managing chronic conditions and improving overall strength and vitality.',
    who: 'Vasti therapy may be recommended for individuals experiencing: Chronic constipation or irregular bowel habits; Lower back pain, joint pain, or stiffness; Neurological or nerve-related conditions; Digestive weakness or bloating; Joint degeneration and arthritis; Fatigue and weakness due to chronic illness.',
    benefits: [
      'Relieves chronic pain and stiffness',
      'Improves digestion and nutrient absorption',
      'Helps regulate bowel movements',
      'Nourishes nerves and joints',
      'Supports detoxification and tissue strength',
      'Enhances overall energy and mobility.',
    ],
    bodyParts: 'Rectal route (lower digestive tract)',
    duration: 'The administration time of Vasti usually takes 10 to 15 minutes. However, the retention time of the medicated preparation varies based on the type of Vasti.',
  },
  {
    id: 't28',
    name: 'Varma',
    slug: 'varma',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fvarma.webp?alt=media&token=2490d84a-8827-4b15-a82b-d484d59229c4',
    what: 'Varma Therapy is a traditional therapeutic technique that involves gentle and precise stimulation of specific vital points on the body, known as Varma points. These points are believed to be centers where nerves, muscles, bones, and energy pathways intersect. The therapy is performed using controlled touch, pressure, or massage techniques to support the body’s natural healing response.',
    why: 'Over time, stress, injury, poor posture, or chronic illness can lead to blockages, stiffness, or nerve disturbances in the body. Varma Therapy aims to release these blockages, improve nerve communication, and restore functional balance. It is commonly used as a supportive therapy in pain management and rehabilitation.',
    who: 'Varma Therapy may be recommended for individuals with: Neck pain, back pain, or joint pain; Nerve-related conditions; Muscle stiffness or spasms; Sports injuries or post-injury rehabilitation; Headaches or migraines; Reduced mobility or flexibility',
    benefits: [
      'Helps relieve pain and stiffness',
      'Improves nerve function and circulation',
      'Supports muscle relaxation',
      'Enhances mobility and flexibility',
      'Aids in recovery from injuries',
      'Promotes overall balance and well-being.',
    ],
    bodyParts: 'Head and neck\n\nSpine and back\n\nShoulders, arms, and hands\n\nHips, legs, and feet\n\nLocalized areas based on the condition',
    duration: 'Each Varma Therapy session typically lasts 30 to 45 minutes, depending on the area treated and the patient’s condition.',
  },
  {
    id: 't18',
    name: 'Raktamokshana',
    slug: 'raktamokshana',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fraktamokshana.webp?alt=media&token=71c35cc9-f70e-442d-84ef-0a0ca9a7cbe1',
    what: 'Rakta Mokshana is a classical Ayurvedic purification therapy that involves the controlled removal of a small quantity of impure blood from the body. This therapy is performed using specific methods, such as leech therapy or sterile bloodletting techniques, depending on the condition. Rakta Mokshana is traditionally used to eliminate toxins from the blood and restore balance.',
    why: 'According to Ayurveda, many skin, inflammatory, and circulatory disorders are caused by impurities in the blood and excess heat in the body. Rakta Mokshana helps reduce toxin load, relieve inflammation, and improve circulation. By cleansing the blood, the therapy supports the body’s natural healing process.',
    who: 'Rakta Mokshana may be recommended for individuals with: Chronic skin conditions such as eczema, acne, or psoriasis; Recurrent boils, abscesses, or non-healing wounds; Gout or inflammatory joint pain; Varicose veins or localized swelling;Burning sensations or excessive body heat; Certain blood-related or inflammatory conditions.',
    benefits: [
      'Helps purify the blood',
      'Reduces inflammation, pain, and swelling',
      'Supports healing of chronic skin conditions',
      'Improves local circulation',
      'Helps relieve burning sensations and heat imbalance',
      'Supports detoxification and tissue health.',
    ],
    bodyParts: 'Commonly on limbs or localized regions, as clinically indicated',
    duration: 'Each Rakta Mokshana session generally takes 20 to 40 minutes, depending on the method used and the individual’s condition.',
  },
  {
    id: 't12',
    name: 'Netra Tarpanam',
    slug: 'netra-tarpanam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fnetra-tarpanam.webp?alt=media&token=01e02346-f68a-425a-9e6f-cec65bf5239e',
    what: 'Netra Tarpanam is a traditional Ayurvedic eye therapy in which medicated ghee is gently retained over the eyes for a specific duration using a specially prepared herbal dough ring. This therapy helps nourish, lubricate, and strengthen the eyes and surrounding tissues. The medicated ghee used is selected based on the individual’s condition and eye health needs.',
    why: 'The eyes are sensitive organs that are easily affected by strain, dryness, excess screen usage, pollution, and aging. Netra Tarpanam provides deep nourishment to the eye tissues and helps relieve stress and dryness. It is commonly recommended to support visual comfort and maintain long-term eye health.',
    who: 'Netra Tarpanam may be advised for individuals experiencing: Eye strain or tired eyes; Dryness, burning, or irritation in the eyes; Blurred vision; Sensitivity to light; Headaches related to eye strain; Prolonged computer or mobile screen use.',
    benefits: [
      'Lubricates and nourishes the eyes.',
      'Helps reduce dryness, burning, and irritation',
      'Relieves eye strain and fatigue',
      'Supports clarity and comfort of vision',
      'Promotes relaxation of eye muscles',
      'Helps protect eyes from environmental stress.',
    ],
    bodyParts: 'Eyes and surrounding eye area',
    duration: 'Each Netra Tarpanam session typically lasts 20 to 40 minutes, depending on the condition being treated.',
  },
  {
    id: 't22',
    name: 'Karnapooranam',
    slug: 'karnapooranam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fkarnapooranam.webp?alt=media&token=eff0f270-48df-4f1c-952f-1bbaa493f1df',
    what: 'Karna Pooranam is a traditional Ayurvedic therapy in which warm, medicated oil or herbal preparations are gently poured into the ear canal and retained for a specified duration. This therapy is performed with careful technique and supervision to support ear health and balance related sensory functions.',
    why: 'According to Ayurveda, the ears are sensitive to dryness, excess vata, and nerve imbalance, which may lead to discomfort or hearing-related issues. Karna Pooranam helps lubricate the ear canal, nourish the nerves, and restore balance. The warmth and medicinal properties of the oil provide soothing and protective effects.',
    who: 'Karna Pooranam may be advised for individuals experiencing: Ear pain or discomfort; Ringing sensation in the ears (tinnitus); Dryness or itching in the ears; Reduced hearing due to wax accumulation; Headaches related to ear or nerve imbalance; Jaw stiffness or facial discomfort associated with ear strain.',
    benefits: [
      'Helps relieve ear pain and dryness',
      'Supports ear and hearing health',
      'Reduces ringing or buzzing sounds',
      'Nourishes ear tissues and nerves',
      'Helps reduce stiffness in the jaw and neck area',
      'Promotes relaxation and comfort.',
    ],
    bodyParts: 'Ears',
    duration: 'Each session of Karna Pooranam usually lasts 15 to 30 minutes, including preparation and retention time.',
  },
  {
    id: 't11',
    name: 'Takradhara',
    slug: 'takradhara',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Ftakradhara.webp?alt=media&token=1e5ec8bc-f37c-4375-966e-58fcbd31658e',
    what: 'Takra Dhara is a specialized Ayurvedic therapy in which medicated buttermilk (Takra) is gently poured in a continuous stream over specific parts of the body, most commonly the forehead or scalp. The buttermilk used in this therapy is prepared with medicinal herbs and is selected based on the individual’s condition. This therapy is traditionally used to calm the mind, cool the body, and restore balance.',
    why: 'Takra Dhara is primarily used to address conditions related to excess heat, stress, and imbalance in the nervous system. The cooling and soothing nature of medicated buttermilk helps reduce internal heat and provides a calming effect on both the mind and body. This therapy is particularly beneficial where stress, anxiety, or skin-related issues are prominent.',
    who: 'Takra Dhara may be recommended for individuals experiencing: Stress, anxiety, or mental exhaustion; Insomnia or disturbed sleep; Headaches or burning sensations in the head; High body heat or heat-related discomfort; Skin conditions such as dandruff, scalp irritation, or psoriasis; Certain neurological and psychosomatic conditions.',
    benefits: [
      'Calms the nervous system',
      'Helps reduce stress and mental fatigue',
      'High body heat or heat-related discomfort',
      'Improves sleep quality',
      'Provides a cooling and soothing effect',
      'Supports scalp and hair health',
      'Helps manage inflammatory skin conditions',
      'Promotes mental clarity and relaxation.',
    ],
    bodyParts: 'Takra Dhara is mainly performed on:\n\nForehead and scalp\n\nIn some cases, the full body.',
    duration: 'Each session of Takra Dhara typically lasts 30 to 60 minutes, depending on the condition being treated.',
  },
  {
    id: 't23',
    name: 'Lepam',
    slug: 'lepam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Flepam.webp?alt=media&token=4054e610-6f95-453e-86f4-3a579fe2ce57',
    what: 'Lepam is a traditional Ayurvedic external therapy in which specially prepared herbal pastes are applied over specific areas of the body. These herbal formulations are selected based on the individual’s condition and are applied in a specific thickness and direction. Lepam allows medicinal properties of herbs to be absorbed through the skin, helping to relieve localized discomfort and inflammation.',
    why: 'In Ayurveda, many health conditions arise due to inflammation, toxin accumulation, or imbalance in tissues and circulation. Lepam therapy is used to directly address these issues at the affected area. Since it works externally, it provides targeted relief while supporting internal healing without stressing the digestive system.',
    who: 'Lepam therapy is commonly recommended for individuals experiencing:  Joint pain, muscle pain, or stiffness; Swelling or inflammation; Skin conditions such as eczema, psoriasis, or rashes; Sports injuries or localized trauma; Headaches or localized pain; Heat-related conditions or burning sensations;',
    benefits: [
      'Helps reduce pain and inflammation',
      'Improves local blood circulation',
      'Relieves swelling and stiffness',
      'Supports healing of skin and soft tissues',
      'Provides cooling or warming effect based on the drugs used',
      'Promotes relaxation and comfort.',
    ],
    bodyParts: 'Lepam therapy can be applied to various body parts, depending on the condition, including:  Joints (knees, shoulders, elbows); Back and neck; Head or forehead; Abdomen; Affected areas of the skin',
    duration: 'The duration of Lepam therapy typically ranges from 20 to 45 minutes per session, depending on the condition being treated and the type of herbal paste used. The total number of sessions is advised based on the individual’s health needs and response to therapy.',
  },
  {
    id: 't26',
    name: 'Shiro Abhyangam',
    slug: 'shiro-abhyangam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fshiro-abhyangam.webp?alt=media&token=7e7d8052-787e-438c-938b-059308b23ceb',
    what: 'Shiro Abhyangam is an Ayurvedic head massage that focuses on the head, neck, shoulders, and sometimes the face. The word comes from “Shiro” (head) and “Abhyangam” (oil massage). It is done using herbal oils by gentle, rhythmic movements.',
    why: 'It is done to improve sleep, to relieve headaches, to support hair health, to balance doshas (especially helpful for Vata and Pitta imbalance), to relax the nervous system, and to improve mental clarity.',
    who: 'People with stress or anxiety, those with insomnia or poor sleep, headache or migraine sufferers, people with hair or scalp problems, those with mental fatigue or poor concentration, individuals with Vata or Pitta imbalance, anyone seeking relaxation and rejuvenation.',
    benefits: [
      'Reduces stress and anxiety',
      'improves sleep quality',
      'strengthens hair and scalp',
      'relieves headaches and tension',
      'enhances memory and concentration',
      'balances doshas',
      'promotes overall relaxation.',
    ],
    bodyParts: 'Head (scalp), neck and shoulders, sometimes face and ears.',
    duration: 'Typically 20–40 minutes per session, depending on the purpose and individual.',
  },
  {
    id: 't27',
    name: 'Valuka Swedana',
    slug: 'valuka-swedana',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fvaluka-swedana.webp?alt=media&token=73adb783-4e3f-4bf0-8bda-d47267236475',
    what: 'Valuka Swedana is an Ayurvedic dry heat therapy using heated sand. “Valuka” means sand, and “Swedana” means sudation or sweating therapy. It is a treatment where warm, roasted sand is filled in a cloth bag and applied to painful or swollen body parts to produce heat and relieve symptoms.',
    why: 'To reduce pain, stiffness, and swelling, to relieve inflammation in joints, to improve blood circulation, to reduce Kapha and Vata imbalance, to ease muscle or joint discomfort.',
    who: 'People with arthritis (especially rheumatoid arthritis), those with joint pain, knee pain, ankle pain, individuals with swelling or stiffness, people with localized inflammatory conditions, anyone needing dry heat therapy where oil massage is not suitable.',
    benefits: [
      'Reduces pain and swelling',
      'decreases stiffness',
      'improves movement of joints',
      'dries up excess fluid accumulation',
      'gives warmth and comfort to painful areas.',
    ],
    bodyParts: 'Knees, ankles, elbows, wrist, back or shoulder (depending on the condition), any localized painful area.',
    duration: 'Usually 15–25 minutes, done daily or on alternate days depending on the condition.',
  },
  {
    id: 't25',
    name: 'Pada Abhyangam',
    slug: 'pada-abhyangam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fpada-abhyangam.webp?alt=media&token=14b27e01-7a86-45c1-adc7-b99990aeeb13',
    what: 'Pada Abhyanga is an Ayurvedic foot massage therapy using herbal oils. It is a traditional Ayurvedic foot massage that applies warm herbal oil to the feet, followed by gentle, rhythmic massage techniques.',
    why: 'To relax the body and mind, to reduce stress and fatigue, to improve sleep, to soothe tired legs and feet, to balance Vata dosha, to enhance blood circulation.',
    who: 'People with stress or anxiety, those with insomnia or disturbed sleep, individuals with foot pain, heel pain, or leg fatigue, people who stand or walk for long hours, anyone seeking relaxation and grounding.',
    benefits: [
      'Promotes deep relaxation and sleep',
      'reduces leg pain and swelling',
      'improves blood circulation',
      'strengthens foot muscles and nerves',
      'calms the nervous system.',
    ],
    bodyParts: 'Feet (soles, toes, heels), ankles, lower legs (sometimes).',
    duration: 'Typically 15–30 minutes per session',
  },
  {
    id: 't24',
    name: 'Mukha Lepam',
    slug: 'mukha-lepam',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fmukha-lepam.webp?alt=media&token=609a0a38-6ddb-4558-a1af-0a99ddb1cd7b',
    what: 'Mukha Lepam is an Ayurvedic herbal face pack treatment used for skin purification and rejuvenation. It is an Ayurvedic herbal paste application on the face, made from medicinal powders, fresh herbs or clays to improve skin health.',
    why: 'To cleanse and detoxify facial skin, to reduce acne, pigmentation, and blemishes, to improve complexion and glow, to remove excess oil and impurities, to soothe and cool irritated skin, for anti-aging and skin nourishment.',
    who: 'People with acne or oily skin, those with dull or uneven complexion, individuals with pigmentation, dark spots, tanning, people with dry or sensitive skin, anyone wanting natural glow and skin rejuvenation.',
    benefits: [
      'Clear, bright, and glowing skin',
      'reduced acne, pimples, and marks',
      'controls oil production',
      'tightens pores',
      'improved skin texture',
      'anti-aging and wrinkle reduction',
      'soothes inflammation and redness.',
    ],
    bodyParts: 'Entire face and sometimes neck',
    duration: 'Usually 15–20 minutes, paste is applied, kept to dry partially, and then washed off.',
  },
  {
    id: 't14',
    name: 'Pichu',
    slug: 'pichu',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Fpichu.webp?alt=media&token=e75d6674-5b2c-49f5-91b6-3a7f95d09ff8',
    what: 'Pichu is a gentle Ayurvedic external therapy in which a soft cotton pad soaked in warm, medicated oil is placed over a specific area of the body for a prescribed period of time. This allows the medicinal properties of the oil to slowly penetrate the tissues, providing nourishment and sustained therapeutic effect.',
    why: 'Pichu therapy is used to deliver localized nourishment, reduce dryness, and relieve pain or stiffness. It is particularly helpful in conditions caused by tissue dryness, nerve irritation, or prolonged strain. The slow and continuous contact of medicated oil supports deeper relaxation and healing of the affected area.',
    who: 'Pichu therapy may be recommended for individuals experiencing: Neck pain, lower back pain, or joint pain; Muscle stiffness or spasms; Nerve-related discomfort; Headaches or stress-related tension; Spinal strain or disc-related discomfort; Weakness in specific body areas',
    benefits: [
      'Provides deep nourishment to tissues',
      'Helps reduce pain, stiffness, and dryness',
      'Supports nerve relaxation and strength',
      'Improves local circulation',
      'Promotes relaxation and comfort',
      'Enhances mobility in the affected area.',
    ],
    bodyParts: 'Head or scalp; Neck and shoulders; Lower back or spine; Knees and other joints; Any localized area requiring treatment.',
    duration: 'Each Pichu session typically lasts 20 to 40 minutes, depending on the area treated and the individual’s condition.',
  },
  {
    id: 't20',
    name: 'Acupuncture',
    slug: 'acupuncture',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/shreevarma-india-location.firebasestorage.app/o/therapy%20page%2Facupuncture.webp?alt=media&token=0fdeeb3d-b4a9-4089-866b-78f5fca3c12e',
    what: 'Acupuncture means “to puncture with needles.” “Acu” means needle and “puncture” means to prick or pierce. Acupuncture means healing the body by inserting fine needles at specific points to balance energy and relieve pain.',
    why: 'To reduce pain, to improve blood circulation, to relax muscles and nerves, to balance the body’s energy flow, to support natural healing, to reduce stress and improve overall well-being.',
    who: 'People with back pain, neck pain, joint pain, those with migraine or headaches, individuals with stress, anxiety, or insomnia, people with sciatica, arthritis, or muscle stiffness, those with sinus issues or digestive problems, anyone looking for holistic, drug-free therapy.',
    benefits: [
      'Pain relief',
      'reduced stress and tension',
      'better sleep',
      'improved digestion',
      'enhanced energy and mood',
      'reduced inflammation',
      'supports healing of chronic conditions.',
    ],
    bodyParts: 'Needles are applied on hands, feet, back, face, legs, ears, and specific meridian points across the body.',
    duration: '20–30 minutes per session, often done weekly or as advised.',
  },
];
